### ISSUE TITLE
port to minipass >= 5.0.0

### ISSUE THREAD

**Issue by bastien-roucaries** [tapjs/libtap#54]
Hi,

For debian could you port libtab to minipass 5.0.0 ?

I am stuck with https://github.com/tapjs/tapjs/pull/506

Thanks you

**Comment by isaacs** [comment]
You are posting a comment on a repo that is no longer used by modern versions of tap, referencing an issue from 5 years ago.

No, I'm not going to do this for free. I'm happy to discuss a paid engagement if you'd like me to allocate time for this, or you are welcome to fork the code and take ownership of that work yourself, as the license explicitly allows.
